# Site settings
baseurl = "http://kattappurathu.com/"
languageCode = "en-us"
title = "Kattappurathu | A slice of God's Own Travancore"
theme = "hugo-agency-theme"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-111622234-1"

[params]
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "Kattappurathu"
  description = "Our home is a home stay in the upper kuttanad region of central travancore in Kerala, India. A bunglow with character surrounded with fruit trees and flowering plants, on MC Road between Thiruvalla and Changanacherry. Close to Kuttanad Kumarakom backwaters, close enough to the verdant hills and forests of the Western Ghats. Visit Konni Elephant camp, alleppy kuttanad backwaters, cheruthenaruvi in pattanamthitta."

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico" #Need to update

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Navigation
  [params.navigation]
    brand = "Kattappurathu"
    # Optional logo as brand stored in img/
    #logo = "logo.svg"
    services = "What to Expect"
    portfolio = "Sights"
    about = "Where are we?"
    # team = "Stay"
    contact = "Contact"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    [[menu.postpend]]
      url = "http://prasanthabr.github.io/kuttanadan/"
      name = "Tales & Fables"
      weight = 10


  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "Welcome to our little slice of God's Own Travancore"
    subtitle = "welcome to the slow lane"
    buttonText = "Stay with Us"


  # Services section
  [params.services]
    enable = true
    title = "What to Expect"
    subtitle = "Kattappurathu is an old bungalow facing the Main Central Road, in the quaint little village of Ezhinjillam (colloquially known as Idinjillam). <br> The property, though not very large, is teeming with life. Local fruit trees like mango, jack fruit, flowering plants that attract butterflies and dragon flies, a flurry of native birds (including, recently, a visiting peahen), squirrels, an odd Iguania, a family of mongoose and a few proud Indian monitor lizards add up to the ‘life’ in the property. Fish grown in a pond within the land and a few varieties of poultry are treated as part of the family. The house overlooks paddy fields of Kuttanadu. In the fields and farm area behind the property, one may encounter a few turtles, owls and beetles. We do encourage our guests to explore our extended property and enjoy nature at its best. We take pride in being a green oasis in the middle of a fast developing region, try to celebrate life, and take care not to harm the animals that make our place their home.<br><br>We offer the staying quarters for our guests on the top floor of our house. The top floor, with two quarters, common areas and common kitchen, is self contained, with independent access and provides relative privacy from our home downstairs.<br><br>Apart from the bungalow, we have an adjacent free standing wooden granary (see the facing picture) that brings nostalgic memories of a grand era of farming in Kuttanad. Till recently we used to keep paddy cultivated in our fields in this granary. Now, we maintain it for our guest to see and our next generation to remember the toil of our ancestors.<br><br>We invite you to visit us with an open mind, be a Kuttanad farmer in spirit and savour in the sounds, smells, sights and experiences of Central Tranvancore, while staying with us as our guests."

    [[params.services.row]]

    [[params.services.row.list]]
      icon = "fa-camera-retro"
      title = "Native Sights"
      description = "We offer the warmth of a home on the banks of extensive paddy fields, where one can witness the kuttanadan sun setting into endless expanse of paddy fields behind coconut trees. An old ara or grannary on the property is unique to the region. A mansion built in the 60s inspired by art deco completes the sights. The larger of our boarding rooms have extensive windows to the paddy fields, which also brings in a light breeze into the house."
      url = "#"

    [[params.services.row.list]]
      icon = "fa-bug"
      title = "Native Flora Fauna"
      description = "We like to think of our home as a green oasis. If you look beyond the two overarching mango trees, you shall find jackfruits, berries, plantain, banana and tamarinds. The property is also home to an eclectic mix of animals and birds. We would encourage you to slow down, savour in the sights and smells that are on offer at our home."
      url = "#"

    [[params.services.row.list]]
      icon = "fa-bell-slash"
      title = "Calm & Quiet"
      description = "The property is right on the main central road in Kerala, but cocooned in the tiny village of Ezhinjillam. This allows you a quiet peaceful slice of Kerala, away from the hustle of a routine Kerala. And if you are indeed feeling the urge to experience the hustle, we encourage you to visit the old markets, steeped in history, with its own canal system, in Changanacherry"
      url = "#"

  # Portfolio section
  [params.portfolio]
    enable = true
    # All projects defined in their own files. You can find example projects
    # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    title = "Around Us.."
    subtitle = "Idinjillam is a small village connecting two growing towns of Changanachery and Thiruvalla, in the Central Travancore region of Kerala. To our west lie the plains and paddy fields of Kuttanad with its interweaving backwaters and rivers. To our east is the famed cardamom hills and forests of the western ghats. Central Travancore is the seat of royalty and culture with quite a few unexplored gems of Kerala.</br></br> For the traveller who wants to take it slow, our home, provides a much needed respite in itself. </br></br> We offer comfortable, safe homestay facilities at Idinjillam at our home."

    [params.portfolio.modal]
      client = "Hotstop"
      distance = "Distance"
      category = "Category"
      buttonText = "Close Location"


    # About section
  [params.about]
    enable = true
    title = "That Point on the Map!"
    subtitle = "Our homestay is in Idinjillam in the Central Travancore region of Kerala, with the kuttanadan paddy fields to our west and the hills of the western ghats to our east."
    endpoint = "Make us the destination itself"

    # The events will be listed from the top to the bottom.
    # All images are stored under 'static/img/about'.
    # Replace them with your own.
    [[params.about.events]]
      img = "1.jpg"
      date = "Kattappurathu"
      title = "Stay in an elegant mansion house"
      description = "This is an elegant, imposing mansion house overlooking paddy fields and lush gardens. It is conveniently connected by road and rail. Its hospitable owners offer a sumptuous base to those who love to get an authentic experience of what God's Own Country has to offer. They have a wealth of experience to advise and help guests personalise their travel experience from paddy fields to backwaters, house boats, elephant rides, temples, churches, mural paintings, art and unparalleled cuisine of Kerala. We welcome you to stay with us."

    [[params.about.events]]
      img = "2.jpg"
      date = "Ara"
      title = "Old wooden granary to store grains"
      description = "The old granary has seen a few summers where grain from the fields that were owned by the hosts, were stored in it after the harvest. In the kuttanad region of Kerala, paddy is the staple crop, where farmers grow paddy twice a year. The rice from the paddy is boiled in large copper vessels and dried in the hot Kerala sun."

    [[params.about.events]]
      img = "3.jpg"
      date = "After the Harvest"
      title = "Ducks, fishes, fisherman and the festival of summer"
      description = "Large paddy fields of the kuttanad region are a sight to behold in all seasons. While the lush green paddy swaying in the wind is ubiquitous in pictures; the explosion of life after the harvest is an equally appealing sight. The flooded fields are filled with fish, birds and ducks and is an experience reserved for those who call this land home."

    [[params.about.events]]
      img = "4.jpg"
      date = "Seasonal fruit trees"
      title = "Under the shade of the mango trees"
      description = "The property, though small, is filled with trees and plants. There are mangoes, a variety of jackfruits and local plaintain that one can enjoy straight from mother nature."


 # # Team section
 # [params.team]
 #   enable = true
 #   # Possibility to center items
 #   #center = true
 #   title = "Stay with us"
 #   subtitle = "We are available on airbnb for bookings"
 #   description = "we have three options for your stay. "
 #   # All team member's pictures are stored under 'static/img/team'.
 #   # Replace them with your own too.
 #   # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
 #   [[params.team.members]]
 #     img = "1.jpg"
 #     name = "Kattappurathu"
 #     link = "https://www.airbnb.co.in/rooms/20781029?s=51"
 #     position = "2 Bed & Large Common Area"
 #     #reportsTo = "CTO"
 #     #livesIn = "[Munich, Germany](#some-maps-url)"
 #     #scope = [
 #     #  "UX for [member dashboard](#)",
 #     #  "Maintainer for [awesome-project](#)",
 #     #  "Open Source [community management](#)"
 #     #]
 #     # For bio markdown and even multiline strings are available.
 #     # bio = """Kay is an awesome Lead Designer with heaps of experience in the field of UX.
 #     # She worked at Pied Piper for years until they went belly up."""
 #     social = [
 #       ["fa-bed", "https://www.airbnb.co.in/rooms/20781029?s=51"],
 #       ["fa-shower", "https://www.airbnb.co.in/rooms/20781029?s=51"],
 #       ["fa-snowflake-o", "https://www.airbnb.co.in/rooms/20781029?s=51"],
 #       ["fa-wifi", "https://www.airbnb.co.in/rooms/20781029?s=51"]
 #     ]
#
 #   [[params.team.members]]
 #     img = "2.jpg"
 #     name = "Kattappurathu Kudumbam"
 #     link = "https://www.airbnb.co.in/rooms/20700152?s=51"
 #     position = "2 Bed & Large Common Area"
 #     social = [
 #       ["fa-bed", "https://www.airbnb.co.in/rooms/20700152?s=51"],
 #       ["fa-shower", "https://www.airbnb.co.in/rooms/20700152?s=51"],
 #       ["fa-snowflake-o", "https://www.airbnb.co.in/rooms/20700152?s=51"],
 #       ["fa-wifi", "https://www.airbnb.co.in/rooms/20700152?s=51"]
 #     ]
#
 #   [[params.team.members]]
 #     img = "3.jpg"
 #     name = "Kattappurathu Veedu"
 #     link = "https://www.airbnb.co.in/rooms/21442528?s=51"
 #     position = "4 Bed & Large Common Area"
 #     social = [
 #       ["fa-bed", "https://www.airbnb.co.in/rooms/21442528?s=51"],
 #       ["fa-shower", "https://www.airbnb.co.in/rooms/21442528?s=51"],
 #       ["fa-snowflake-o", "https://www.airbnb.co.in/rooms/21442528?s=51"],
 #       ["fa-wifi", "https://www.airbnb.co.in/rooms/21442528?s=51"]
 #     ]
#
 # # Client section
 #   [params.clients_list]
 #     enable = false
 #     # Possibility to center items
 #     center = true
 #     # Optional client title specifying the involvement
 #     title = "book with us through airbnb"
#
 #     # All the clients' logos are stored under 'static/img/logos'.
 #     # Replace them with your clients's logos.
 #     # Suggestion: .svg in the size of 280px*80px looks good
 #     [[params.clients]]
 #       logo = "airbnb.png"
 #       link = "https://www.airbnb.co.in/rooms/21442528?s=51"
#
 #     [[params.clients]]
 #       logo = "designmodo.jpg"
 #       link = "#"

  # Contact section
  [params.contact]
    enable = true
    title = "Contact us"
    subtitle  = "Use the form or sent us a note on [rajan@kattappurathu.com](mailto:rajan@kattappurathu.com)"
    buttonText = "Send message"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.
    # postURL = "https://example.com/mailout/"

    email = "kabrahammathew@gmail.com"

    # Success and error message overwrite for async contact form
    #thanks = "Thank you for awesomely contacting us."
    #error = "Message could not be send. Please contact us at mail@example.com instead."

    # 'warning' defines error messages for invalid inputs
    [params.contact.form.name]
      text = "Your Name *"
      warning = "Please enter your name."

    [params.contact.form.email]
      text = "Your Email *"
      warning = "Please enter your email address."

    [params.contact.form.phone]
      text = "Your Phone *"
      warning = "Please enter your phone number."

    [params.contact.form.message]
      text = "Your Message *"
      warning = "Please enter a message."

      # Add optional form fields to identify contact forms
      #[[params.contact.form.hidden]]
      #  name = "someID"
      #  value = "example.com"
      #
      #[[params.contact.form.hidden]]
      # Special values for name such as "page" and "site" will be autofilled
      #  name = "page"

  # Footer section
  [params.footer]
    enable = true
    copyright = "2017 [kattappurathu.com](http://kattappurathu.com)"

    [[params.footer.social]]
      icon = "fa-twitter"
      link = "#"

    [[params.footer.social]]
      icon = "fa-facebook"
      link = "#"

    [[params.footer.social]]
      icon = "fa-email"
      link = "#"

    [[params.footer.quicklinks]]
      text = "Privacy Policy"
      link = "location.html"

    [[params.footer.quicklinks]]
      text = "Terms of Use"
      link = "#"
